### ISSUE TITLE
Font and icon assets

### ISSUE THREAD

**Issue by NateWr** [NateWr/pkp-admin-sketches#2]
**Font**
The mockups use the [Noto Sans](http://www.google.com/fonts/specimen/Noto+Sans) font. What do we think about this? It's an [interesting project from Google](https://www.google.com/get/noto/) to build a font that achieves visual harmony across as many languages as possible. I think it's a good candidate for PKP in the long term. But there may be some complications to work around regarding when and under what conditions we are loading which character sets. I'd need to test how character-set fallbacks are handled.

**Icon Font**
I just used the [Octicons](https://octicons.github.com/) icon font because I am using it on another project and knew I could slot it in easily. But the PKP projects have a pretty large set of icon needs and Octicons probably won't be sufficient. The ideal scenario would be to at some point build a custom font sent from open-source icons, using [icomoon](https://icomoon.io/) or something similar. In the meantime, what do you think about something like [FontAwesome](http://fortawesome.github.io/Font-Awesome/)? Normally I'd consider it bloat but it might give us a leg-up and we can trim things down at a later stage. By that point it might make sense to jump straight to SVG anyway.

**Comment by asmecher** [comment]
**Fonts**

I have no experience with web fonts. I'm all in favour of something like you describe; since we're using UTF-8 in all the ways we should, I think a multilingual-savvy project like Noto Sans will suit us well.

**Icons**

Currently we've got our own sprite set:
https://github.com/pkp/pkp-lib/blob/master/templates/images/structure/sprites.png

We do have some pretty specific sprite needs so I think we'll probably have to continue maintaining this in the long term, but any leverage we an get from an externally-maintained set that's somewhat harmonious would be great, particuarly when it comes to standard widgets.

As far as what "harmonious" means, I'm the last person to offer a trustworthy opinion :)

**Comment by NateWr** [comment]
@asmecher Ok, I will continue working with Noto Sans and we'll work out which character sets to load and when down the road.

I will be happy the day we remove that sprite sheet from the repo. :) In the meantime, I will try to adopt a very broad set (probably FontAwesome) when implementing new design templates. [The font is OFL but the LESS/CSS is MIT](http://fortawesome.github.io/Font-Awesome/license/). Can you confirm this is ok for the project?

**Comment by asmecher** [comment]
It says GPL friendly, so I'm content to take their word for it.

**Comment by NateWr** [comment]
Switch to FontAwesome was done in 1e9529f1a9d11f89deeeec71dca301448c49e40d and Noto Sans already in place. With FontAwesome, I've configured the LESS so that we only un-comment the icons we need. We should save ~30kb this way, though the font files themselves are still a bit heavy.
